### ISSUE TITLE
Atomic Heart некорректно определяются кнопки клавиатуры. 

### ISSUE THREAD

**Issue by Ratevandr** [Castro-Fidel/PortWINE#111]
В atomic heart (vk play лаунчер) некорректно определяются буквенные кнопки. Работают "управляющие" клавиши вроде пробела. При попытке переназначить клавиши в настройках, игра показывает вопросительный знак, но кнопка начинает работать в игре (что очень не удобно). Пробовал выбирать английскую и русскую раскладку перед стартом, пробовал включать USE_US_LAYOUT в настройках portwine, не помогло.
Proton_LG-8-25-1
Nwest DXVK 2.3-13 и VKD3D 1.1-3727
PortProton v. 1.3
scripts v.2239
OS: Arch Linux (KDE) (пробовал wayland и Xorg, результат одинаков)
[portproton.txt](https://github.com/Castro-Fidel/PortWINE/files/13779943/portproton.txt)

**Comment by Ratevandr** [comment]
Выставил в настройках KDE (System-settings -> Keyboard --> Layout) Английскую раскладку над русской, после этого все стало нормально работать. Удивительно конечно.

**Comment by Castro-Fidel** [comment]
Это нормальное поведение wine в любой системе. Для обхода есть галка в настройках при запуске exe: USE_US_LAYOUT
