### ISSUE TITLE
не работает интернет

### ISSUE THREAD

**Issue by myt4444** [Castro-Fidel/PortWINE#114]
при запуске выдает ошыбку (You will need to check internet connection,and press Repeat for repeat download) ничего не помогает я использывал разные дистрибутивы но проблема только в debian вожможно потомучто я подключен к итернету через вайфай
![арапр](https://github.com/Castro-Fidel/PortWINE/assets/137760671/ccf252e0-86f2-4606-9069-2000d67c3b8e)

**Comment by Castro-Fidel** [comment]
В debian последнем, есть проблемы с локалями. Если запустить из терминала, то скорее всего будет ругаться на них.

**Comment by myt4444** [comment]
в терминале тоже самоє

**Comment by myt4444** [comment]
нужно біло отключить firejail
