### ISSUE TITLE
ошибка загрузки d8vk-1.0.tar.xz

### ISSUE THREAD

**Issue by Folivora** [Castro-Fidel/PortWINE#117]
После установки запускаю portproton. Что-то скачивается, бегает прогрессбар пока не попытается скачать "d8vk-1.0.tar.xz". После этого каждый раз ошибка с текстом "Проверьте интернет соединение и
нажмите Repeat для повторной попытки скачивания". Репит ничего не дает - всё тоже самое.

**Comment by Folivora** [comment]
Вот здесь https://github.com/AlpyneDreams/d8vk/releases/tag/d8vk-v1.0 есть возможность вручную скачать "d8vk-1.0.tar.gz" (расширение gz вместо xz). Не нашел где в скрипте поменять расширение

**Comment by Castro-Fidel** [comment]
Считаю что эти ошибки связаны: https://github.com/Castro-Fidel/PortWINE/issues/118

**Comment by Folivora** [comment]
Нет, не связаны. Данную ошибку я парировал скачиванием и распаковкой архива в ручную. К тому же, если бы эти ошибки были связаны, логичнее было бы закрыть тот запрос, а не этот

**Comment by gvozd18** [comment]
> После установки запускаю portproton. Что-то скачивается, бегает прогрессбар пока не попытается скачать "d8vk-1.0.tar.xz". После этого каждый раз ошибка с текстом "Проверьте интернет соединение и нажмите Repeat для повторной попытки скачивания". Репит ничего не дает - всё тоже самое.
На FTP данного файла просто нет. Я уже проверил FTP с которого пытается скачивать

**Comment by Castro-Fidel** [comment]
> > После установки запускаю portproton. Что-то скачивается, бегает прогрессбар пока не попытается скачать "d8vk-1.0.tar.xz". После этого каждый раз ошибка с текстом "Проверьте интернет соединение и нажмите Repeat для повторной попытки скачивания". Репит ничего не дает - всё тоже самое.
> > На FTP данного файла просто нет. Я уже проверил FTP с которого пытается скачивать

Он у всех скачивается с апстримного гита проекта d8vk.
В течении часа добавлю на фтп.

**Comment by Castro-Fidel** [comment]
Добавил на FTP архивом tar.xz.
Проверяйте.

**Comment by gvozd18** [comment]
Спасибо. Завелось

**Comment by Castro-Fidel** [comment]
> Спасибо. Завелось

Хорошо.

**Comment by gvozd18** [comment]
> > > После установки запускаю portproton. Что-то скачивается, бегает прогрессбар пока не попытается скачать "d8vk-1.0.tar.xz". После этого каждый раз ошибка с текстом "Проверьте интернет соединение и нажмите Repeat для повторной попытки скачивания". Репит ничего не дает - всё тоже самое.
> > > На FTP данного файла просто нет. Я уже проверил FTP с которого пытается скачивать
> 
> Он у всех скачивается с апстримного гита проекта d8vk. В течении часа добавлю на фтп.

Интересно. А почему у меня не захотел качаться. Я Wireshark посмотрел куда стучится скрипт, на какой  IP адреc. Других адресов в дампе не было.
