### ISSUE TITLE
Добавление Авто-установщика Nvidia GFN(GeForce Now)

### ISSUE THREAD

**Issue by norz3n** [Castro-Fidel/PortWINE#13]
Приветствую.

Есть предложение добавить авто-установщик GeForce Now в PortProton, так как есть вероятность что под стандартным лаунчером не будет задержки длиной в 3-5 секунд.

Сразу говорю - под Proton лаунчер работать **НЕ БУДЕТ**
Нужно собирать специальную версию Wine

> https://github.com/aabgrall/wine-base-geforcenow

Вот ссылка на неё
Буду очень благодарен если это реализуется

Discord-тэг: Norz3n#5686

**Comment by Castro-Fidel** [comment]
Актуально предложение? Просто не хочется спонсировать нвидию, ибо аллергия на их маркетинг. Да и GFN дорогой и есть русский аналог в виде VK Play Cloud.
