### ISSUE TITLE
Порт протон ужасно работает с русским языком и кириллицой в целом.

### ISSUE THREAD

**Issue by W1nKille3r** [Castro-Fidel/PortWINE#14]
Когда я пытаюсь открыть любую русскую программу через PortProton. Она не имеет интерфейса, или вовсе крашится ссылаясь на шрифты. Это довольно критично т.к я вынужден использовать английские версии программ (Да я не только запускаю игры через порт протон и что!?). Тем более он показал себя с виду совместимости с Windows приложениями на высшем уровне. Любое вмешательство с помощью Wine (он криво работает и крашится). PoL (Play on Linux) вовсе отвалился, теперь нельзя что либо установить вообще. Вот и приходится использовать Port Proton.

Кстате странно что пиратская сборка CS V6 (Sergey-ts) не болеет подобным. И работает как будто под линукс она и писалась. Потому что на нативном Windows он вылетал с ошибкой ограничения объектов. Теперь я знаю виновника.

Надеюсь получу адекватный ответ, потому что я не думаю что это проблема конкретно протона. И это можно как - то пофиксить. К примеру с помощью тех же юзов WineTricks. Но они же не знают как вшивать софт для PortProton - а верно?

edit: Bottles не работает вовсе, и выяснять почему у меня тупо времени не хватало. Начнётся лето, да и окунусь с головой с программами на Linux.

**Comment by Castro-Fidel** [comment]
Запусти PortProton вкладка настройки wine, там есть WINETRICKS с гуи
сделанным специально для PortProton.
И такие вопросы лучше писать в дискорде, ибо вероятность помощи будет
больше.

ср, 18 мая 2022 г., 20:54 W1nKille3r ***@***.***>:

**Comment by Castro-Fidel** [comment]
Закрываю.
