### ISSUE TITLE
Добавить возможность устанавливать свои приложения/игры

### ISSUE THREAD

**Issue by Danik2343** [Castro-Fidel/PortWINE#15]
Добавить возможность устанавливать свои приложения/игры
Допустим нужно приложение поставить, а его нет в PortProton(PortWINE), только в виде установочного файла, нужно
установить через .exe файл, в WINETRICKS тоже нет программы/игры

**Comment by Danik2343** [comment]
И можно добавить возможность создания вкладок для установленных приложений/игр.

**Comment by NikMAX2077** [comment]
> Добавить возможность устанавливать свои приложения/игры Допустим нужно приложение поставить, а его нет в PortProton(PortWINE), только в виде установочного файла, нужно установить через .exe файл, в WINETRICKS тоже нет программы/игры

Через эту софтину можно запускать любой exe`шник и устанавливать так же как в винде. А вот главное меню и правда неудобное, я им даже не пользуюсь, просто запускаю exe`шники из папки с игрой.

**Comment by Castro-Fidel** [comment]
Закрыл по причине возможности запуска сторонних игр и программ изначально.
