### ISSUE TITLE
не запускается

### ISSUE THREAD

**Issue by id2746** [Castro-Fidel/PortWINE#165]
При запуске с ярлыка ничего не происходит и появляется сообщение об ошибке:
Не удалось запустить PortProton.
Не удалось сменить каталог на "/***/***l/PortProton/data/scripts/". Нет такого файла или каталога.

При этом каталог существует и если запускать через:
bash /***/***l/PortProton/data/scripts/start.sh
то все portproton открывается корректно.

При установке из *.deb пакета проблемы нет

**Comment by Castro-Fidel** [comment]
При установке из *.deb пакета проблемы нет

А при какой установке есть проблемы?

Путь содержит пробелы?

**Comment by Loadngg** [comment]
У самого такая проблема была. Надо убрать кавычки в `~/.local/share/applications/PortProton.desktop` в полях `Path` и `Icon`. Заново логинишься и всё работает. 

Аналогичный файл должен быть и в `то_куда_вы_поставили/PortProton/PortProton.desktop`

**Comment by Castro-Fidel** [comment]
Исправлено в крайних обновлениях скриптов.
