### ISSUE TITLE
Can't upgrade Fedora due `portproton`

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [Castro-Fidel/PortWINE#167]
I'm going to upgrade Fedora 39 to Fedora 40 via Software Center. But I've got such a message:
```
Error running transaction: package portproton-2:1.5-1.x86_64 is already installed
```

I had the same issue on upgrade from 38 to 39. Workaround was:
1. Delete portproton
2. Disable repo
3. Upgrade
4. Enable repo and install portproton

**Comment by Boria138** [comment]
> I'm going to upgrade Fedora 39 to Fedora 40 via Software Center. But I've got such a message:
> ```
> Error running transaction: package portproton-2:1.5-1.x86_64 is already installed
> ```
> 
> I had the same issue on upgrade from 38 to 39. Workaround was:
> 1. Delete portproton
> 2. Disable repo
> 3. Upgrade
> 4. Enable repo and install portproton

Hmm I built PortProton under Fedora 40 long before the release, so this error should not be there, as it usually occurs when the package is not built for the version you want to upgrade to, maybe this is an isolated case, I think it's worth leaving the error open so that anyone else can post here if anything happens

**Comment by Boria138** [comment]
When trying to upgrade from 39 to 40 Fedora with this command

```
sudo dnf system-upgrade download --releasever=40
```

Everything goes through without problems, the error is not reproduced

**Comment by muhammadyusuf-kurbonov** [comment]
> When trying to upgrade from 39 to 40 Fedora with this command
> 
> ```
> sudo dnf system-upgrade download --releasever=40
> ```
> 
> Everything goes through without problems, the error is not reproduced

Also try using Software Center, please

**Comment by muhammadyusuf-kurbonov** [comment]
I've switched to the Flatpak version. So this error, I hope, won't occur anymore.

**Comment by Boria138** [comment]
> > When trying to upgrade from 39 to 40 Fedora with this command
> > ```
> > sudo dnf system-upgrade download --releasever=40
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything goes through without problems, the error is not reproduced
> 
> Also try using Software Center, please

I figured it out, there was a problem with the version, now it won't happen again and the error can be closed
