### ISSUE TITLE
Запускать еще один exe файл вмести с игрой

### ISSUE THREAD

**Issue by EDEN45** [Castro-Fidel/PortWINE#18]
В некоторых играх хочется использовать тренеры, надо запустить его и потом игру. Как это сделать не нашел.

**Comment by master-of-darkness** [comment]
увы, но такого не возможно. Пробывал поганять с софтом для кс, даже не смог провести иньекцию.

**Comment by Capsick21** [comment]
Нельзя ли это запустить в одной среде wine?

**Comment by VanoMajukin** [comment]
Господа, ознакомтесь https://linux-gaming.ru/2022/10/03/portproton-%d0%b7%d0%b0%d0%bf%d1%83%d1%81%d0%ba-%d0%b2%d1%82%d0%be%d1%80%d0%be%d0%b3%d0%be-%d0%bf%d1%80%d0%b8%d0%bb%d0%be%d0%b6%d0%b5%d0%bd%d0%b8%d1%8f%d0%b8%d0%b3%d1%80%d1%8b/
