### ISSUE TITLE
Gamemode not run Linux Mint 20.03

### ISSUE THREAD

**Issue by Mackey86** [Castro-Fidel/PortWINE#19]
Goverlay показывает что gamemode выключен. В стимоских играх в тоже время все нормально. Попробовал поставить убуну 22.04. Там все в порядке варианте. Куда можно посмотреть чтобы решить? Игра если важно Captain of Industry

**Comment by Castro-Fidel** [comment]
По факту gamemode работает и запускает контейнер со всеми оптимизациями, но портированный мангохад внутри контейнера не видит его, из за этого и обманывает.
