### ISSUE TITLE
Исправление работы UI (лишний обратный слэш)

### ISSUE THREAD

**Issue by SergeyKomVl** [Castro-Fidel/PortWINE#208]
https://github.com/Castro-Fidel/PortWINE/blob/c661fa70f73c68dab7a53689776dbbdd582016ff/data_from_portwine/scripts/functions_helper#L2138

Обратный слеш в конце строки лишний

**Comment by Castro-Fidel** [comment]
Исправили в версии скриптов 2301. Спасибо.
