### ISSUE TITLE
Невозможно запустить ярлык из PortProton, если в ярлыке содержатся некоторые символы

### ISSUE THREAD

**Issue by Maks1mS** [Castro-Fidel/PortWINE#213]
![image](https://github.com/Castro-Fidel/PortWINE/assets/36362599/a016b327-53a9-4973-94ed-20daae938ca8)

Проверено на символах - ', ", `.

**Comment by Castro-Fidel** [comment]
', " - символы экранизации
ПЕРЕМЕННАЯ=`command` - выполнение команды и присвоение выхлопа переменной
По этому нельзя их использовать.

Добавим проверку и удаление этих символов. Спасибо.

**Comment by Castro-Fidel** [comment]
Исправлено в версии 2305
