### ISSUE TITLE
Добавить поддержку flatpak

### ISSUE THREAD

**Issue by neg-serg** [Castro-Fidel/PortWINE#22]
Думаю это было полезно тем кто не хотел бы по каким-то причинам тянуть lib32-* либы себе в систему.

**Comment by Castro-Fidel** [comment]
Flatpak версии не будет в принципе.
Возможно когда-нибудь appimage, но на данный момент нет таких ресурсов для реализации данной версии.

**Comment by gmankab** [comment]
@Castro-Fidel, а почему флатпак не планируете?

я бы очень хотел ставить портпротон из флатхаба, потому что ставится либо одной командой, либо через гуй

плюс не надо бцдет тянуть в систему миллионы зависимостей
