### ISSUE TITLE
Ubuntu 24.04 

### ISSUE THREAD

**Issue by sergeyfil1** [Castro-Fidel/PortWINE#225]
Стоит ubuntu 24.04, установил все зависимости и порт протон все запускается без ошибок, при запуске установки клиента lesta game окно скачивания клиента открывается и тут же закрывается и ни чего не происходит, пробовал и в иксах и в вайланде без разницы в чем может быть проблема? Запуск в терминале показывает -  

Info: The first mirror in used: CDN
 
 Info: Check update... 
 Info: Scripts version in git = 2310 
 Info: Scripts version local = 2310 

 Info: PW_SCREEN_RESOLUTION=1920x1080 
 Info: PW_SCREEN_PRIMARY=HDMI-A-1 

 
;;;;;;;;;;;
||||||||||||||
|||||||||||||||||||||||||||||||||||||
 Info: /home/sergey/PortProton/data/dist/PROTON_LG_9-7/share/wine/mono is symlink. OK. 
 Info: /home/sergey/PortProton/data/dist/PROTON_LG_9-7/share/wine/gecko is symlink. OK. 
 Info: /home/sergey/PortProton/data/dist/PROTON_LG_9-7/share/wine/mono is symlink. OK. 
 Info: /home/sergey/PortProton/data/dist/PROTON_LG_9-7/share/wine/gecko is symlink. OK. 
 Info: RUNTIME is enabled 
 Info: Gamemod is not installed or disabled in vars script or db file: PW_USE_GAMEMODE=0 

 Info: DXVK v.1.10.3-28 in use 
 Info: VKD3D-PROTON v.1.1-2602 in use 
 Info: Try copy WINE files... 
 Info: Try create symlink DXVK files... 
 Info: Try create symlink VKD3D files... 

 Info: MangoHud is disabled 
 Info: vkBasalt is disabled 
 Info: Download Lesta_Game_Center_Install_RU.exe from https://redirect.lesta.ru/LGC/Lesta_Game_Center_Install_RU.exe... 
 OK: File downloaded successfully: Lesta_Game_Center_Install_RU.exe from https://redirect.lesta.ru/LGC/Lesta_Game_Center_Install_RU.exe 
 Info: WINEDIR=/home/sergey/PortProton/data/dist/PROTON_LG_9-7 
 Info: WINEPREFIX=/home/sergey/PortProton/data/prefixes/LGC 
 Info: WINEDLLOVERRIDES=libvkd3d-shader-1=n;d3d12=n;dxgi=n;d3d9=n;d3d10core=n;d3d10=n;d3d10_1=n;d3d11=n;d3dx9_43=n;d3dx9_42=n;d3dx9_41=n;d3dx9_40=n;d3dx9_39=n;d3dx9_38=n;d3dx9_37=n;d3dx9_36=n;d3dx9_35=n;d3dx9_34=n;d3dx9_33=n;d3dx9_32=n;d3dx9_31=n;d3dx9_30=n;d3dx9_29=n;d3dx9_28=n;d3dx9_27=n;d3dx9_26=n;d3dx9_25=n;d3dx9_24=n;d3dx11_43=n;d3dx11_42=n;d3dx10=n;d3dx10_43=n;d3dx10_42=n;d3dx10_41=n;d3dx10_40=n;d3dx10_39=n;d3dx10_38=n;d3dx10_37=n;d3dx10_36=n;d3dx10_35=n;d3dx10_34=n;d3dx10_33=n;d3dcompiler_47=n;d3dcompiler_46=n;d3dcompiler_43=n;d3dcompiler_42=n;d3dcompiler_41=n;d3dcompiler_40=n;d3dcompiler_39=n;d3dcompiler_38=n;d3dcompiler_37=n;d3dcompiler_36=n;d3dcompiler_35=n;d3dcompiler_34=n;d3dcompiler_33=n;nvngx,_nvngx=;steam_api,steam_api64,steamclient,steamclient64=n;dotnetfx35.exe,dotnetfx35setup.exe=b;winemenubuilder.exe= 
 Info: PATH_TO_GAME= 
 Info: PW_WINE_USE=PROTON_LG_9-7 
 Info: PW_VULKAN_USE=1 
 Info: VULKAN_DRIVER_NAME=radv 
 Info: VKD3D_CONFIG=nodxr 
 Info: PW_LD_LIBRARY_PATH=/home/sergey/PortProton/data/tmp/plugins_v16/portable/lib/lib64:/home/sergey/PortProton/data/tmp/plugins_v16/portable/lib/lib32:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases:/overrides/lib/x86_64-linux-gnu:/overrides/lib/i386-linux-gnu:/home/sergey/PortProton/data/dist/PROTON_LG_9-7/lib64:/home/sergey/PortProton/data/dist/PROTON_LG_9-7/lib 
 Info: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin 
 Info: WINEESYNC=0 
 Info: WINEFSYNC=0 
 Info: WINEFSYNC_FUTEX2=0 
 Info: WINEDLLPATH=/home/sergey/PortProton/data/dist/PROTON_LG_9-7/lib64/wine:/home/sergey/PortProton/data/dist/PROTON_LG_9-7/lib/wine 
 Info: WINE_CPU_TOPOLOGY= 
 Info: PW_RUN_GAMESCOPE= 
 Info: LD_LIBRARY_PATH= 

 Info: Update prefix log: 

 Info: Log from RUNTIME and WINE: 
Log WINE:
pressure-vessel-wrap[14585]: E: Cannot run /usr/bin/bwrap: wait status 256
pressure-vessel-wrap[14585]: E: Diagnostic output:
bwrap: setting up uid map: Permission denied

pressure-vessel-wrap[14585]: E: Cannot run /home/sergey/PortProton/data/tmp/libs_v48/pressure-vessel/bin/pv-bwrap: wait status 256
pressure-vessel-wrap[14585]: E: Diagnostic output:
bwrap: setting up uid map: Permission denied

/home/sergey/PortProton/data/scripts/functions_helper: строка 355: 14581 Определяемый пользователем сигнал 1                                          "${pw_yad}" --progress-old --text="$(gettext "Please wait. Installing the") $@
        " --pulsate --hide-text --borders="$PROGRESS_BAR_BORDERS_SIZE" --no-buttons --undecorated --center --skip-taskbar --no-escape --text-align="center" --height=90 --fixed --width="$PROGRESS_BAR_WIDTH_SIZE" --wrap-width="$PROGRESS_BAR_WIDTH_SIZE" --window-icon="$PW_GUI_ICON_PATH/portproton.svg" &> /dev/null  (рабочий каталог: ~/PortProton/data/scripts)

Removing the lock file...
удалён '/tmp/portproton.lock'
OK

**Comment by Castro-Fidel** [comment]
https://linux-gaming.ru/t/obnovlenie-skriptov-2306/870/6?u=castro_fidel
Если в Ubuntu 23.10 или в 24.04 не запускаются игры и в терминале следующая ошибка:
```
pressure-vessel-wrap[32393]: E: Cannot run /usr/bin/bwrap: wait status 256
pressure-vessel-wrap[32393]: E: Diagnostic output:
bwrap: Creating new namespace failed: Permission denied
```

Пропишите следующую команду:
`sudo chmod u+s /usr/bin/bwrap`

**Comment by sergeyfil1** [comment]
> https://linux-gaming.ru/t/obnovlenie-skriptov-2306/870/6?u=castro_fidel Если в Ubuntu 23.10 или в 24.04 не запускаются игры и в терминале следующая ошибка:
> 
> ```
> pressure-vessel-wrap[32393]: E: Cannot run /usr/bin/bwrap: wait status 256
> pressure-vessel-wrap[32393]: E: Diagnostic output:
> bwrap: Creating new namespace failed: Permission denied
> ```
> 
> Пропишите следующую команду: `sudo chmod u+s /usr/bin/bwrap`

Спасибо помогло.
