### ISSUE TITLE
Не работает клавиатура в WoW

### ISSUE THREAD

**Issue by Apollo-74** [Castro-Fidel/PortWINE#227]
Суть сабжа такова, не работают клавиши с буквами, вернее если в чат писать то всё нормально. Но любые действия назначенные на эти клавиши (с буквами) не работают. Допустим ходить персонажем нельзя.
NixOS + flatpak portproton
Wine_lg 9.11
Пробовал другие версии - не помогает.
Бывает такое что заходишь и на время персонаж двигается буквально 1 секунду на клавиши а потом перестает

**Comment by Castro-Fidel** [comment]
Раскладка в системе английская по умолчанию?

**Comment by Apollo-74** [comment]
> Раскладка в системе английская по умолчанию?

В плазме русская стояла, поменял на английскую, заработало, спасибо, можно закрывать ишью :)
