### ISSUE TITLE
Странный WINE требует удаленный доступ

### ISSUE THREAD

**Issue by nikonufrienko** [Castro-Fidel/PortWINE#234]
Скачиваю следующую версию WINE:
![image](https://github.com/Castro-Fidel/PortWINE/assets/25980970/c06fd9cc-5eb8-436f-a713-481acd4f8b08)

Пытаюсь запустить приложение (battle.net) и оно не запускается.

После клика на значок PortProton получаю сообщение с запросом удаленного доступа:
![image](https://github.com/Castro-Fidel/PortWINE/assets/25980970/cdc9077f-bb00-4434-9051-11e5cfa9b6fc)

![image](https://github.com/Castro-Fidel/PortWINE/assets/25980970/aa5e5f35-6c4c-4af0-b874-16bcd340f56e)

Возможно, это беды на стороне KDE, но всё же это настораживает.

**Comment by nikonufrienko** [comment]
А нет, это же поведение воспроизводится с любой версией WINE.

**Comment by Castro-Fidel** [comment]
Не видел такого поведения и никто не жаловался.
Тут лучше запустить PP из терминала и скинуть выхлоп сюда, либо в дискорде.
Если сам PP работает, то создать лог: https://linux-gaming.ru/t/kak-sozdat-log-oshibki/25

**Comment by Htylol** [comment]
@Castro-Fidel это wayland потому что, там код для этого трея в yad ещё с gtk второй версии идёт, с принудительным включением устарелых функций ))) У меня вообще трей не работает из yad )))

**Comment by lapadaviloff** [comment]
@Castro-Fidel у меня при нажатии на иконку в трее  выпазит такое же  сообщение  "запрошен удаленно управляемый сеанс", пункты выбора "файловый менеджер,  диспетчер задач ..." не появляются. Arch-6.9.9, KDE 6.1.2, wayland

**Comment by Boria138** [comment]
При принятие этого PR исправится

https://github.com/Castro-Fidel/PortWINE/pull/236
