### ISSUE TITLE
После последнего апдейта вечный луп на скачку vkd3d-proton.2.6.tar.zst

### ISSUE THREAD

**Issue by Nayfania** [Castro-Fidel/PortWINE#24]
После последнего апдейта вечный луп на скачку vkd3d-proton.2.6.tar.zst
говорит проверьте соединение с интернетом
нажимаешь ок, опять пытается скачать и опять вылетает с ошибкой. и так по кругу до бесконечности
пробовал заново инсталить - таже проблема

**Comment by Castro-Fidel** [comment]
Vkd3d на гитхабе запакован в архив tar.zst и для его распаковки надо установить в систему zstd.
На данный момент выбираю способ решения проблемы. Либо в зависимости добавить пакет, либо использовать портативную версию архиватора.

**Comment by Nayfania** [comment]
да спасибо установка zstd в систему решило проблему

**Comment by Castro-Fidel** [comment]
Добавлено условие: Если нет в системе zstd, то используется портативная версия.
