### ISSUE TITLE
Ubisoft Connect приказал долго жить после своего обновления

### ISSUE THREAD

**Issue by kabachoke** [Castro-Fidel/PortWINE#30]
Юбисофт лаунчер просто сдох, когда загрузил обновление лаунчера.
![Screenshot_20230202_002001](https://user-images.githubusercontent.com/73298492/216166999-69fcd3ad-f519-4188-9ecf-aa6a68e6138c.png)
[upc.exe_138.0.10807_2023-02-02_00-19-42.zip](https://github.com/Castro-Fidel/PortWINE/files/10561728/upc.exe_138.0.10807_2023-02-02_00-19-42.zip)

**Comment by Castro-Fidel** [comment]
###Scripts version 2205### Дата: 01.76.2023 / Размер скачиваемого обновления: 240 мегабайт.
* Обновлен PROTON_LG до версии 8-4
* с версией PROTON_LG_8-4 снова работает игра "Мир Кораблей"
* с версией PROTON_LG_8-4 снова работает лончер "Ubisoft Connect"
