### ISSUE TITLE
Unable to install wmp10 and wmp11 on winetricks

### ISSUE THREAD

**Issue by UltraBurstXD** [Castro-Fidel/PortWINE#311]
Howdy!

As the title suggest I'm unable to install wmp10 and wmp11. So far I've only installed wmp9, but there are games that require wmp11.

Here's the terminal log

~~~shell
# UPDATE PREFIX...
# START WINETRICKS...
# Try to install DLL in prefix: wmp11
# Using winetricks 20240105-next - sha256sum: 929affe9165a1971ce6d07c321add9f77e7d38784cc40bdeb5dedc540e92b23a with wine-9.0 and WINEARCH=win64
~~~

It shows that and automatically exits, when I go to winetricks to see if it was install remains unchecked, which means nothing was done.

**Comment by Castro-Fidel** [comment]
Write a list of games that require wmp10-11. I'll check if possible.

**Comment by UltraBurstXD** [comment]
For now I only know that **Call of Juarez: The Cartel** requires it. I had issues with **Resident Evil: Revelations 2** too, however that one I managed to install wmp9 and worked. But I wanted to install wmp10-11 because of audio stutters. I don't know if it'd help to fix the issue or at least reduce it.

**Comment by UltraBurstXD** [comment]
Alright, here's the list (for now):

1. **Resident Evil: Revelations 2** (Tested thoroughly - doesn't work well with wmp9, although it mitigated a little some problems)
2. **Call of Juarez: The Cartel**

**Comment by UltraBurstXD** [comment]
I managed to install wmp11 by **"clearing prefix"** first and then try to install it again. I guess the first time I tried to install wmp11 I had networking issues while downloading the libs, then winetricks for some reason refused to try to install it again.

Anyway, the workaround fixed the issue, but that brought another one...
