### ISSUE TITLE
Unchecking a library on Winetricks doesn't uninstall it

### ISSUE THREAD

**Issue by UltraBurstXD** [Castro-Fidel/PortWINE#312]
Howdy!

I installed dotnet 3.5 because **L.A Noire** requires it to run. However during installation process there were some errors that I failed to copy for research, nevertheless in the end winetricks said the library was installed with success.

But... The game doesn't run, so I wanted to uninstall the library and try to install it again, but when I uncheck the lib on winetricks it ain't uninstalled. I tried many times, but doesn't work. Or is there another way to uninstall libs? I'm missing something?

**Comment by UltraBurstXD** [comment]
The only way to uninstall or reverse the installation of certain lib for now is **"clear prefix"** option, but that also uninstall others. The button works as factory reset, because it defaults the prefix to default values or state. 

What makes things worse, winetricks or any other component responsible for its management doesn't check if the libs it needs have already been downloaded and are reusable before deleting them and download again!

**Comment by Eljeyna** [comment]
winetricks doesnt have feature to uninstall library, that is it

**Comment by UltraBurstXD** [comment]
Alright, I'll stick with **clear prefix** for now since it does something similar and winetricks doesn't re-downloads libraries that have already been downloaded anymore as stated on fixed issue #313.

Thanks!
