### ISSUE TITLE
Winetricks doesn't check locally if the libs it needs exist before trying to download

### ISSUE THREAD

**Issue by UltraBurstXD** [Castro-Fidel/PortWINE#313]
Howdy!

Yeah, has the tittle suggests winetricks even when the libs it needs have been downloaded it doesn't check locally if they are reusable. It even deletes them and attempts to download again!

Maybe for KBs sized dlls like **__32-binkw32.dll3.0.0.0.zip** it ain't issue... But GBs sized like **windows6.1-KB976932-X64.exe** and **windows6.1-KB976932-X86.exe** ain't cool. I use metered network, and it's big waste to download files that already exist every time I run into issues with prefix and I'm forced to reset it.

**Comment by Castro-Fidel** [comment]
![Screenshot_20240826_135835](https://github.com/user-attachments/assets/7218bf16-6b85-49ff-a138-7e607bbd891a)

Will be added in the next update.

**Comment by Castro-Fidel** [comment]
DONE.
