### ISSUE TITLE
Дефолтный путь установки / захламление домашней директории

### ISSUE THREAD

**Issue by ztx-lyghters** [Castro-Fidel/PortWINE#35]
В юникс-подобных системах для домашних директорий есть достаточно стандартизированные пути для хранения приложений и их конфигураций, такие как **~/.local/share** и **~/.config** соответственно. Предлагаю сменить стандартный предлагаемый путь установки на **$XDG_DATA_HOME/portproton**, либо просто **~/.local/share/portproton**. Раз такие стандарты есть, предлагаю не брать пример с других и не забивать на них, тем самым хоть немного разгрузить корень домашней директории у пользователей.

**Comment by Castro-Fidel** [comment]
При установке из пакета, или репозиториев (Альт, Роса, АУР) PP устанавливается в ~/.local/share и создается симлинк в домашнюю директорию.
При удалении симлинка, он создастся снова. Это пофиксим.

**Comment by Castro-Fidel** [comment]
Пофикшено в Альт, Роса, АУР.
