### ISSUE TITLE
Не запускаются игры с параметром GUI DISABLED CS

### ISSUE THREAD

**Issue by TAforever** [Castro-Fidel/PortWINE#355]
После недавнего обновления перестали запускаться игры через меню с параметром GUI DISABLED CS, через сам portproton все работает как и прежде

**Comment by Htylol** [comment]
@TAforever Ну дак фикс в 2356 версии выходил, не помог что ли?

**Comment by TAforever** [comment]
Нет, не помог

**Comment by Castro-Fidel** [comment]
Не удается воспроизвести проблему.

**Comment by Castro-Fidel** [comment]
Хотя есть идея. Сегодня будет обнова, нужно будет проверить после неё.

**Comment by TAforever** [comment]
https://github.com/user-attachments/assets/ac2fb12f-9ce3-404d-9921-69af274e4d19

**Comment by Castro-Fidel** [comment]
Настройки PP - глобальные настройки - изменить ветку на DEVEL.
В devel обнову с исправлением уже отправил.

**Comment by TAforever** [comment]
> Настройки PP - глобальные настройки - изменить ветку на DEVEL. В devel обнову с исправлением уже отправил.

Исправлено, спасибо!
