### ISSUE TITLE
Трей иконка не работает

### ISSUE THREAD

**Issue by Denizantip** [Castro-Fidel/PortWINE#360]
Скрипт functions_helper проверяет XDG_SESSION_TYPE==tty (O_o) и запускает PortProton/data/themes/tray/tray_gui_pp, который является скомпилированным файлом и который пытается найти функции объявленные в bash скрипте (pw_tray_winefile, pw_tray_taskmgr, open_changelog, tray_icon_click_exit) и не находит их. 
Тут или поменять tty на x11/wayland или довести до ума  tray_gui_pp.

**Comment by Castro-Fidel** [comment]
Что за система? Запуск нативного PP, или flatpak?

**Comment by Htylol** [comment]
@Denizantip В bspwm не работает нормально трей на аппиндикатор, а у яда на. gtk2/3 нормально работает. У bspwm XDG_SESSION_TYPE == tty, у нормальных de x11 или wayland должен быть

**Comment by Denizantip** [comment]
```bash
echo $XDG_CURRENT_DESKTOP 
ubuntu:GNOME
echo $XDG_SESSION_TYPE 
x11
```

yad работает. Но для этого нужно заставить скрипт использовать yad (должно быть tty, а у меня, как и у многих x11/wayland).
У меня такая же проблема была на Ubuntu 20.04. Обновился до 22.04. Тоже самое.

```bash
source PortProton/data/scripts/functions_helper
./PortProton/data/themes/tray/tray_gui_pp 
bash: строка 1: pw_tray_winefile: команда не найдена
bash: строка 1: pw_tray_taskmgr: команда не найдена
bash: строка 1: open_changelog: команда не найдена
bash: строка 1: tray_icon_click_exit: команда не найдена
```


Судя по всему tray_gui_pp пытается запустить функции объявленные в bash. 
А при запуске создаётся новая сессия где эти функции не существуют.

**Comment by Denizantip** [comment]
> Что за система? Запуск нативного PP, или flatpak?

@Castro-Fidel. Ubuntu 24.04. Нативный.

**Comment by Castro-Fidel** [comment]
env LD_LIBRARY_PATH="${PW_LD_LIBRARY_PATH}" "${PW_GUI_TRAY_PATH}/tray_gui_pp" &
 
 Он и должен запускать tray_gui_pp если не bspwm.
 
 Ошибку воспроизвести не могу, новый трей (не yad) работает норм.

**Comment by Castro-Fidel** [comment]
Issue закрыт, ошибка сама пропала, или что?

**Comment by Denizantip** [comment]
@Castro-Fidel 
Проблема не пропала.
Трей иконка очень упрощает процесс запуска второго приложения. 
Поэтому буду каждый раз после обновления скриптов править его чтоб использовалась не нативное приложение. 
Если найду способ как пофиксить обязательно поделюсь

**Comment by Castro-Fidel** [comment]
Интересно что у когне спрашиваю, новый трец работает ОК.
Надо понять почему не отрабатывает у тебя.

**Comment by Denizantip** [comment]
@Castro-Fidel Могу предоставить своё окружение для дебага

**Comment by Htylol** [comment]
@Denizantip в телеграмме как тебя найти?

**Comment by Skullckoor** [comment]
Трабла всё та же. Бинарник tray_gui_pp возвращает результат через вызов `system`. Т.е. через `/usr/bin/sh`, который в DEB (и не только) указывает не на bash.
Из-за чего трэй и не фурычит. Без конца дёргать
```
alias shtobash='sudo rm -f /usr/bin/sh && sudo ln -s bash /usr/bin/sh'
alias shtodash='sudo rm -f /usr/bin/sh && sudo ln -s dash /usr/bin/sh' 
```
тоже не вариант. Да и это не решение проблемы. Надо бинарник переписывать для вызова не через 'system' (он априори /usr/bin/sh вызывает), а напрямую bash. В СИ не селён. ХЗ как это лечить и поможет ли в принципе.
Зато старый трэй работает.

Короче... в `PortProton/data/scripts/functions_helper` есть строки. Их там 3 штуки, но заменить достаточно строку 4746:
`    if [[ "$XDG_SESSION_TYPE" == "tty" ]] ; then`
меняем на 
`    if [[ "$XDG_SESSION_TYPE" == "tty" ]] | [[ $(readlink "/usr/bin/sh") != "bash" ]] ; then`
и запускается старый трэй. Костыльно, но 1) работает 2) не мешает тем, у кого `/usr/bin/sh -> bash` .
Причем даже иконки у каждого пункта отображаются (у меня через бинарник они не отображаются в принципе).

Единственное, что смущает `/usr/bin/sh` тоже может по другому пути лежать. Так что не без подводных камней.
