### ISSUE TITLE
Лига легенд перестала работать после того как игра обновилась

### ISSUE THREAD

**Issue by coldloaded** [Castro-Fidel/PortWINE#39]
После обновления игра перестала работать. Клиент лиги работает нормально, однако при попытке запустить непосредственно игру вылетает такая ошибка.

![image](https://user-images.githubusercontent.com/93398219/230175505-6ec6f81b-ce0f-46fd-b292-5259779a9ab8.png)

Прикрепил архив с crash dump'ом
[crash_dump.zip](https://github.com/Castro-Fidel/PortWINE/files/11162153/crash_dump.zip)

UPD
Запустил игру в режиме дебага, вылетела такая ошибка
007c:err:seh:dispatch_exception unknown exception (code=c0000420) raised
При поиске в сети обнаружил, что такая же проблема появилась и у других играюших в лол с вайна после последнего обновления
https://github.com/kyechou/leagueoflegends/issues/83
https://www.reddit.com/r/leagueoflinux/comments/12c8w4p/last_patch_did_it_again/
https://www.reddit.com/r/leagueoflinux/comments/12cbqeq/update_of_leagueoflegendsgit_script_and_the_aur/
https://old.reddit.com/r/leagueoflinux/comments/12cei7t/patch_137_feedback_megathread_transition_to_64bit/
Корень проблемы в том, что разрабы прекратили поддержку 32битных систем.

**Comment by Capsick21** [comment]
Нашел решение работающее на lutris 
SOLUTION

League of Legends -> Config -> Runner Options -> (enable Advanced options on top right) -> DXVK Version -> change it to v1.10.3 -> Save -> Play

**Comment by coldloaded** [comment]
Пофикшено, проверил
