### ISSUE TITLE
How do I launch a game with command arguments?

### ISSUE THREAD

**Issue by UltraBurstXD** [Castro-Fidel/PortWINE#407]
Howdy!

I'm having some issues with Tom Clancy's Splinter Cell Blacklist, it keeps crashing and I read from different sources that launching it with `-offline -offline_mode` command line arguments may fix the issue. However, I don't know how or where I can put the launch options before the game starts.

**Comment by daniliammo** [comment]
![1](https://github.com/user-attachments/assets/f39cd51b-af57-42ac-9e4d-cafe811c6c24)
![2](https://github.com/user-attachments/assets/e127d29f-2315-4de2-9b28-c216e2dde290)
![3](https://github.com/user-attachments/assets/3a16ada0-6e7a-4c4f-9606-00e7f5ea89ab)
