### ISSUE TITLE
Не может обновиться

### ISSUE THREAD

**Issue by ulrickno94** [Castro-Fidel/PortWINE#44]
Вылетает окно, предлагает обновиться, и не получается - не может скачать master.tar.gz ни с гитхаба, ни с ftp, ошибка "проверьте интернет соединение" Разумеется, с инетом все ок.
Из лога:
Info: Check update... 
 Info: OK! 
 Info: Scripts version in github = 2202 
 Info: Scripts version local = 1000 
######################################################
 Info: Update scripts... 
 Error: Failed to download master.tar.gz from GitHub. 
 Info: Try download master.tar.gz from FTP 
 Error: Failed to download master.tar.gz from FTP.

**Comment by Castro-Fidel** [comment]
Исправлено в версии:
###Scripts version 2215### Дата: 18.08.2023 / Размер скачиваемого обновления: 8 мегабайт
* добавлено зеркало скриптов: https://gitlab.eterfund.ru/Castro-Fidel/
* отключено создание сторонних (не работающих) ярлыков средствами wine (при использовании версий wine отличных от proton)
