### ISSUE TITLE
Завершение игр из Epic Games Launcher

### ISSUE THREAD

**Issue by alex2844** [Castro-Fidel/PortWINE#457]
@Castro-Fidel 
Привет
Я изначально, хотел сделать так же https://github.com/Castro-Fidel/PortWINE/commit/723596bb161ac6e3999d843cd28e2861388ba8e8
Т.е. искать portwine_exe
Но во время тестов, находил игры (например: Saint row) - которые запускают лаунчер, которые запускают другой исполняемый файл
Поэтому я и использовал winedbg для получения процессов в текущем префиксе, и фильтровал из него системные, а так же процессы самого egs

**Comment by Castro-Fidel** [comment]
Привет. Проверь теперь.

И пингани меня в ТГ пожалуйста.

**Comment by alex2844** [comment]
Привет
Проверил, теперь не вылетает 👍
По поводу телеграмма - без понятия куда писать :)
