### ISSUE TITLE
Как теперь запустить exe под PortProton ?

### ISSUE THREAD

**Issue by zorn-v** [Castro-Fidel/PortWINE#5]
Раньше (по крайне мере в 51) был скрипт `portproton.sh` который куда то делся в последнийх версиях.
Я на базе этого делаю "ярлыки" в PlayOnLinux для тех игр которые "глючат" без протона.
Что то вроде
```bash
#!/bin/bash

`dirname "$0"`/../PortProton/data/scripts/portproton.sh '../../Games/Lightmatter/LightmatterSub.exe'
```
Как в новых версиях такое провернуть ?

ЗЫ. Скрипты вручную делаю, изменяю только путь к ехе.

**Comment by Castro-Fidel** [comment]
Скрипт старт заменяет тот скрипт.
И зачем всё усложнять, создаавай ярлыки по ПКМ на ехе и запустить с помощью
PortProton.
В следующий раз, пиши к нам на сервер Дискорд.


ср, 28 апр. 2021 г., 03:20 zorn-v ***@***.***>:

**Comment by zorn-v** [comment]
> Скрипт старт заменяет тот скрипт.

Сорян, дело было в относительных путях в моих скриптах. Я пробовал portproton на start поменять и вылазил стандартный диалог (потому что `[ -f path_to_exe ]` не находил файл), вот и создал исушку )

> И зачем всё усложнять, создаавай ярлыки по ПКМ на ехе и запустить с помощью

Ну я как то привык что у меня игрухи в одном месте - в PlayOnLinux.

> В следующий раз, пиши к нам на сервер Дискорд.

Не нашел где куда.
