### ISSUE TITLE
Уменьшить (добавить?) таймаут проверки обновлений при запуске

### ISSUE THREAD

**Issue by NikMAX2077** [Castro-Fidel/PortWINE#60]
В случае проблем с сестью или доступом к серверу обновлений, portproton зависает на проверке обновлений, что приводит к вечному (или очень долгому, я не дождался) запуску. Пришлось временно отключить сеть для запуска игры.
Предлагаю сделать таймаут автоматической проверки обновлений в районе 3-10 секунд, а текущее значение оставить для ручной проверки. Лично мне дороже надежность и время запуска, чем частота обновлений.

**Comment by Castro-Fidel** [comment]
###Scripts version 2215### Дата: 18.08.2023 / Размер скачиваемого обновления: 8 мегабайт
* добавлено зеркало скриптов: https://gitlab.eterfund.ru/Castro-Fidel/

таймаут так же добавлен.
