### ISSUE TITLE
Переназначились кнопки DualShock4

### ISSUE THREAD

**Issue by Ardash** [Castro-Fidel/PortWINE#65]
Выявил в DeathStrandingDC из-под Epic Launcher 
3D API: "Стабильные DXVK 1.10.3-28 и VKD3D 1.1-2602"
WINE: PROTON_LG_8-11
PREFIX: DEFAULT
[EpicGamesLauncher.exe.ppdb.gz](https://github.com/Castro-Fidel/PortWINE/files/12491474/EpicGamesLauncher.exe.ppdb.gz)

В текущей 2217 съехали кнопки Options (на Share) и Touchpad (на Options).
В 2215 все работало и работает нормально (отката до 2216 нет в сохраненных скриптах).

OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: **6.3.9** 
Shell: bash 5.2.15 
DE: GNOME 43.6

**Comment by Castro-Fidel** [comment]
Если запускать с новыми скриптами, но на версии WINE: PROTON_LG_8-11, проблема пропадает?

**Comment by Ardash** [comment]
Сначала я попробовал пойти по пути перебора версий WINE, но результата это не дало.
Зато я выяснил, что проблема возникает из-за изменения набора libs_v43 на libs_v44.
Сначала я начал грешить на SDL (так как раньше я уже разбирался с проблемой с раскладкой клавиатуры в связке DOSBox-Debian), но дело не в нем. Постепенно заменяя файлы в 44 файлами из 43 я пришел к тому, что проблема кроется где-то в pressure-vessel, который, как я понял, некий аналог контейнера и является фундаментальным столпом. Где искать его исходники я пока не разобрался.

Таким образом, пока что мое решение проблемы - не использовать libs_44, а остаться на libs_43.

**Comment by Ardash** [comment]
Со свежим обновлением PortProton докачивается PROTON_LG_8-15-1. 
Если произвести откат скриптов до версии 2215 (последний набор на libs_43) и запустить PROTON_LG_8-11, то геймпад работает нормально.
Если после этого (с набором libs_43) выбрать PROTON_LG_8-15-1, то геймпад ломается. Более того, после этого геймпад оказывается сломан в том числе и в PROTON_LG_8-11.

**Comment by Ardash** [comment]
В последнем обновлении джойстик вообще перестал работать.

**Comment by Castro-Fidel** [comment]
> В последнем обновлении джойстик вообще перестал работать.

На Xbox контроллере все ок.
Дуалшок могу проверить в следующий вторник.

Завтра посмотрю как можно порешать более быстрым способом.

**Comment by Castro-Fidel** [comment]
Сегодня при обновлении скриптов 2275:
* исправлена работа геймпадов от Sony Playstation (спасибо Ardash за выявление проблемы)

После обновления прошу проверить у себя, отчитаться и закрыть issue.

**Comment by Castro-Fidel** [comment]
[test_ds.tar.gz](https://github.com/Castro-Fidel/PortWINE/files/14967702/test_ds.tar.gz)
Прошу проверить. Распаковать в каталог scripts с заменой файлов.

**Comment by Ardash** [comment]
> [test_ds.tar.gz](https://github.com/Castro-Fidel/PortWINE/files/14967702/test_ds.tar.gz) Прошу проверить. Распаковать в каталог scripts с заменой файлов.

Проблема в Death Stranding, запущенном из Epic ушла. Считаю проблему решенной.

Появилась связанная(?) проблема. Выявлена на Breathedge из GOG, запущенном непосредственно с исполняемого exe-файла (без всяких лаунчеров).
В версии 2261 геймпад работает; в версии 2274, а также с распакованным поверх 2274 test_ds.tar.gz - геймпад не обнаруживается.
Поищу еще что-нибудь с геймпадом из GOG и уточню.


Еще есть мелкий незначительный недочет: допустим у меня установлен 2261, запускаю exe-файл, обнаруживается наличие обнлвлений, обновляется, сразу после обновления в заголовке все та же версия 2261. При повторном запуске уже правильная версия 2274

**Comment by Ardash** [comment]
В Breathedge вопрос решился более ранним PROTON_LG_8-25-2. 
Проблему считаю решенной. Спасибо за помощь.
