### ISSUE TITLE
Не могу обновить портпротон. 

### ISSUE THREAD

**Issue by Vochatrak-az-ezm** [Castro-Fidel/PortWINE#67]
Пытается скачать libs_v44.tar.xz и просто сбрасывает закачку. Потом пытается скачать с ftp и тоже сбрасывает.
Зашел на гитхаб, нормально скачал этот архив. 

Есть способ хотя бы подсунуть скачанный архив, что бы ПортПротон смог обновиться?

**Comment by Castro-Fidel** [comment]
Можно вручную обновить, распаковав архив в каталог data/tmp

**Comment by Vochatrak-az-ezm** [comment]
Спасибо. 
А нельзя ли добавить к скрипту, что бы он пытался докачать файл, вместо того, что бы удалять недокаченный кусок и начинать заново? 
Что бы не клинило компьютер при проблемах с интернетом, сделать ограниченное число попыток. Скажем 3-5.

**Comment by Castro-Fidel** [comment]
###Scripts version 2218### Дата: 03.09.2023 / Размер скачиваемого обновления: 8 мегабайт
* улучшена проверка RTX видеокарт
* добавлена проверка на гибридную графику NVIDIA + intel/amd (спасибо Boria138)
* добавлена переменная "__VK_LAYER_NV_optimus=NVIDIA_only" при включении "PRIME_RENDER_OFFLOAD" (спасибо Boria138)
* включена докачка файлов при проблемах со скачиванием
* удаление предыдущих версий libs и plugins происходит только при успешном завершении скачивания новых версий
* скачивание можно пропустить и использовать PP с предыдущими версиями библиотек (кроме WINE и библиотек Vulkan API)
* по умолчанию сделан выбор PROTON_LG и WINE_x.x_LG
* добавлена возможность использования по умолчанию стабильных версий DXVK и VKD3D (добавлением export PW_VULKAN_USE=1 в user.conf)
* исправлена ошибка c VKD3D_FEATURE_LEVEL 12_0 с запуском игр на стабильных версиях DXVK и VKD3D
* исправлена установка STALCRAFT

Проверяем. Пишем отзыв.

**Comment by Vochatrak-az-ezm** [comment]
Удалил протон, портпротон начал его качать, докачивает где то до 70% и сбрасывает закачку. 
Потом пытается стянуть с ftp но там вообще без вариантов. 
Так что, не помогло.
Версия портпротона 2219

**Comment by Castro-Fidel** [comment]
Уже давно переведено скачивание с wget, на curl. После чего нет таких проблем.
Если проблема всё еще актуальна, то напишите об этом и переоткройте данную ветку.
