### ISSUE TITLE
Бесконечное обновление при запуске

### ISSUE THREAD

**Issue by SkanerSoft** [Castro-Fidel/PortWINE#68]
Привет! Не могу запустить, после последнего обновления выдает вот такую картину. Она происходит уже больше часа.

![image](https://github.com/Castro-Fidel/PortWINE/assets/13809475/e095b1df-9b13-432f-848f-ab48a06c9f1e)

**Comment by Castro-Fidel** [comment]
Привет, попробуй запустить в терминале:
portproton --reinstall

**Comment by SkanerSoft** [comment]
Попробовал.

https://github.com/Castro-Fidel/PortWINE/assets/13809475/8ffb53bf-18bf-413e-8350-175fa26d5fb5

Немного поясню: руками я никуда не лез, всё по дефолту, как работает из коробки. Пару дней назад запускал игру, и в этот момент всё обновилось.

Поиграл, закрыл, а сегодня не могу запустить. Между этими событиями не запускал.

**Comment by Castro-Fidel** [comment]
Что за система? Были ли обновления ОС?
Если после обновления самого PP он запустился и работал, то большАя вероятность того, что дело вовсе не в PP. Но всё равно, надо разобраться что бы в такой ситуации явно была указана причина случившегося, а не уход в бесконечный цикл.

**Comment by SkanerSoft** [comment]
Linux Mint 20.3 Cinnamon
Обновления пакетов были, но PP вроде среди них не фигурирует.

Точно обновилось ядро на то, что на скрине.
![image](https://github.com/Castro-Fidel/PortWINE/assets/13809475/ab67297f-ed5f-438f-abc9-8d18ccd97039)

**Comment by SkanerSoft** [comment]
Также, в рамках этого бесконечного цикла в файл current_var_ver постоянно записывается следующее содержимое:
`#!/usr/bin/env bash
#Author: Castro-Fidel (linux-gaming.ru)
#SCRIPTS_NEXT_VERSION=2219
########################################################################
export PW_MANGOHUD=0
export MANGOHUD_CONFIG=cpu_stats,cpu_temp,cpu_mhz,cpu_color=2e97cb,cpu_text=CPU,gpu_stats,gpu_temp,gpu_core_clock,gpu_mem_clock,vulkan_driver,gpu_name,gpu_color=2e9762,gpu_text=GPU,vram,vram_color=ad64c1,ram,ram_color=c26693,io_color=a491d3,frame_timing=1,frametime_color=00ff00,time,arch,wine,wine_color=eb5b5b,engine_color=eb5b5b,background_alpha=0.2,font_size=24,background_color=020202,text_color=ffffff,toggle_hud=Shift_R+F12,resolution,vkbasalt
#export PW_XKBD_RU_HACK=1
export PW_RT_MOUNT_RO=("")
export PW_RT_MOUNT_RW=("/media" "/mnt" "/run/media/${USER}" "${PORT_WINE_PATH}")
#export PW_SANDBOX_HOME_PATH="${PORT_WINE_PATH}"
export PW_NO_ESYNC="1"
export PW_USE_GAMEMODE="1"
export PW_FORCE_USE_VSYNC="2"
export PW_LOG="0"
export PW_USE_TERMINAL="0"
export PW_WINEDBG_DISABLE="1"
export PW_WINDOWS_VER="10"
export WINEARCH="win64"
export PW_LIBS_VER="_v44"
export GDK_BACKEND="x11"
export PW_USE_GSTREAMER="1"
export PW_USE_D3D_EXTRAS="1"
export PW_PREFIX_NAME="DEFAULT"
export WINE_WIN_START="start /wait /high /unix"
export WINE_ALLOW_XIM="0"
export PW_USE_SHADER_CACHE="1"
export PW_WINE_CPU_TOPOLOGY="disabled"
export STAGING_SHARED_MEMORY="1"
export PROTON_DISABLE_LSTEAMCLIENT="0"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"
export PW_MANGOHUD_x32="0"
export PW_USE_EAC_AND_BE="1"
###GTK_CONFIG###
# export GTK_DATA_PREFIX=
# export GTK_THEME="Adwaita:dark"
###DEFAULT_WINE###
export PW_WINE_USE="PROTON_LG"
export PW_PLUGINS_VER="_v12"
export PW_FAKE_DLSS_VER="230506"
###WINE_PROTON_LG###
export PW_LG_VER="8-14"
export PW_PROTON_LG_VER="PROTON_LG_${PW_LG_VER}"
###WINE_PROTON_GE###
export PW_WINE_LG_VER="8.5"
export PW_WINE_LG_VER="WINE_${PW_WINE_LG_VER}_LG"
export PW_WINE_FULLSCREEN_FSR="1"
###DXVK_AND_VKD3D###
export VKD3D_LIMIT_TESS_FACTORS="32"
export D8VK_VER="1.0"
export DXVK_STABLE_VER="1.10.3-28"
export DXVK_GIT_VER="2.2-164"
export VKD3D_STABLE_VER="1.1-2602"
export VKD3D_GIT_VER="1.1-3556"
###PREFIX_VERSION###
export DOTPFX_VER="48v1"
export DEFPFX_VER="v1"
export PROGPFX_VER="v1"
export PW_MUST_WINEDLLOVERRIDES="steam_api,steam_api64,steamclient,steamclient64=n;dotnetfx35.exe,dotnetfx35setup.exe=b,winemenubuilder.exe="
#################################################################
export optirun_on=""
export DXVK_CONFIG_FILE="${PORT_WINE_PATH}/data/dxvk.conf"
#################################################################
pw_install_dll_in_prefix ()
{
    case $PW_PREFIX_NAME in
        DEFAULT) export PW_MUST_HAVE_DLL="d3dx9 d3dcompiler_43 physx mfc42 vcrun2022 sandbox" ;;
         DOTNET) export PW_MUST_HAVE_DLL="physx mfc42 vcrun2019 faudio dotnet48" ;;
              *) export PW_MUST_HAVE_DLL="" ;;
    esac
}
########################################################################
add_in_start_portwine ()
{
    echo " "
}
########################################################################
add_in_stop_portwine ()
{
    echo " "
}
export -f add_in_stop_portwine
########################################################################
pw_other_fixes () 
{
    echo ""
}
`

После этого файл очищается (точнее удаляется) и опять записывается этим же содержимым.
