### ISSUE TITLE
How to add very old Proton versions?

### ISSUE THREAD

**Issue by Chromiell** [Castro-Fidel/PortWINE#69]
Hello, sorry if I'm asking this question in English, but I'm not fluent in Russian and I can only understand the general meaning of sentences with Google Translate.

Quick question: is there a way to add Proton 5.13 to PortProton? I'd like to play Kingdom Hearts 3 and apparently that game works with Proton 5.13 (the official version from Valve) out of the box, but in PortProton it seems I can only add Proton versions 7 or 8, is it possible to add 5.13 manually or from the Graphical User Interface?

Also thank you very much for this project, I just recently found out about this and it works great!

**Comment by Ardash** [comment]
Have you tried unpack proton to ~/PortWINE/PortProton/data/dist/?

**Comment by Castro-Fidel** [comment]
You can try as written above, but the probability of launching is minimal. I'm closing it, since support for older versions will not be added.
