### ISSUE TITLE
Нужно добавить отключение композитора при запуске.

### ISSUE THREAD

**Issue by Vochatrak-az-ezm** [Castro-Fidel/PortWINE#7]
В плазме композитор отключается - **qdbus org.kde.KWin /Compositor suspend**
Включается - **qdbus org.kde.KWin /Compositor resume**
Соответственно нужно добавить первое перед запуском, второе после. 

Так же добавить подобные команды как минимум для Гнома. 
Ну и переменную для отключения всего этого, если кому не надо.

**Comment by 1zmena** [comment]
Возможность отключения добавить нужно обязательно, тк на блобе nvidia, включенном ForceFullCompositionPipeline=On и некоторых композиторах (marco из mate) выключение композитинга приносит больше вреда чем пользы. (в Eve online появляется тиринг)

**Comment by Boria138** [comment]
Полагаю можно закрыть

**Comment by Castro-Fidel** [comment]
Да, поддержка добавлена. Закрываю.
