### ISSUE TITLE
язык не переключается

### ISSUE THREAD

**Issue by Mackey86** [Castro-Fidel/PortWINE#75]
После последнего обновления, в котором написано что принудительно включается латинская раскладка для исправления управления. Теперь язык не переключается вообще никак до перезагрузки. Ubuntu 23.04

**Comment by Castro-Fidel** [comment]
Функция работает только при условии поставленной галки USE_US_LAYOUT.
Но перепроверю.

**Comment by Mackey86** [comment]
Спасибо! У меня галочка не стоит.

**Comment by Boria138** [comment]
> Спасибо! У меня галочка не стоит. 

Странное поведение конечно, так как без этой галочки вообще нечего не происходит, но попробуй вести в консоли ``setxkbmap``

**Comment by Mackey86** [comment]
WARNING: Running setxkbmap against an XWayland server

**Comment by Boria138** [comment]
> WARNING: Running setxkbmap against an XWayland server
> 
> 

А, так у тебя Wayland, тогда тебе вообще это функция нечего сломать не могла, так как setxkbmap работает только в x11, копай в другую сторону почему у тебя не работает раскладка, вины PortProton в этом нет

**Comment by Mackey86** [comment]
Да, после этой команды и ломается. Но чуть более внимательнее посмотрел. в консоли продолжает работать переключение, а ломается в chrome. и whatsdesk, но он тоже вроде хром использует. Странно конечно что все происхожит со снятой галочкой.

**Comment by Boria138** [comment]
> Да, после этой команды и ломается. Но чуть более внимательнее посмотрел. в консоли продолжает работать переключение, а ломается в chrome. и whatsdesk, но он тоже вроде хром использует. Странно конечно что все происхожит со снятой галочкой.

Прежде чем добавлять это, я несколько раз проверил что всё работает, но только в иксах, чуть позже тогда переделаю код под Wayland

**Comment by Mackey86** [comment]
Спасибо!!!

**Comment by Boria138** [comment]
@Castro-Fidel Можешь проверить не отрабатывает ли setxkbmap при закрытие PortProton даже без галочки, может я с условиями ошибся, и не заметил так как тестил только в X11

**Comment by Boria138** [comment]
@Mackey86 Слушай, добавь пожалуйста в user.conf 
``PW_USE_US_LAYOUT=0``
И отпиши помогло ли это

**Comment by Mackey86** [comment]
> @Mackey86 Слушай, добавь пожалуйста в user.conf `export PW_USE_US_LAYOUT=0` И отпиши помогло ли это

ДА! Помогло, супер!

**Comment by Castro-Fidel** [comment]
if [ "$PW_USE_US_LAYOUT" != "0" ]; then
        setxkbmap
    fi
    
    Конечно. Когда переменной нет, она тоже не ровна 0. 
    Надо всегда с 1 сравнивать. В общем завтра будет обнова с фиксом.
