### ISSUE TITLE
А порт протон может работать на arm процессоре ?!

### ISSUE THREAD

**Issue by InfernalWolf666** [Castro-Fidel/PortWINE#84]
Привет, дело такое, я купил одноплатный компьютер на ARM процессоре rockchip 3588 - Orange pi 5 plus !

дело вот в чём от производителя мне понравился Ubunty и arch linux .

Я по инструкции в интернете смог запустить на операционке armbian linux и ubuntu, steam приложение скачать игру DreadOut 1 и даже получить артефактную , но всё же графику!!!

следовал вот такой инструкции - https://jamesachambers.com/installing-steam-on-the-orange-pi-5-with-armbian/

Но из-за проблем собранной людьми этих OS у меня то bluetooch никогда не работает, то 4к изоюражение фиолетовое, вообщем они чтото не так изначально настраивают в Линуксе изза чего у меня проблемы (

Я к сожалению Linux стал пользоваться неделю назад, я незнаю ничего, я нуб просто конченный

Может ли Ваш порт протон работать на кривом arch linux от orange pi производителя?! Тоесть мне не нужен именно стим, просто игра распакованная что бы запустить её .exe но именно на Arm процессоре ?!
Но если и steam будет работать , ещё отличнее !!!

Я сгорем пополам всё же смог установаить aur - какойто yay и получать от туда программы!

yay мне прилетел pkgbuild , я вводил команду makepkg -si  что бы его собрать и он собрался, так как поддерживал ARM процессор.

**Comment by InfernalWolf666** [comment]
Просто обидно, когда вместо линукса устанавливаю android OS , то он спокойно тянет Genshin impact , причем реально достойно , не ультры конечно же..... но нужен сенсорный экран (((  для просто возможности поиграть... , клаву мышь ни одна андроид игра конечно же не распознает....

А так хотя бы просто в Darkest Dungeon 1 или 2 поиграть на мини пека, я бы был очень рад

**Comment by Ardash** [comment]
Я не автор проекта и мой ответ может оказаться не точным.
Wine, на основе, которого сделан Proton занимается, очень грубо говоря, обманом приложения, делая вид, что это приложение запускается в окружении Windows. Wine не занимаетcя эмуляцией процессора, а просто напрямую транслирует вызовы.
Игры, которые вы пытаетесь запустить изначально собраны под x86_64 архитектуру, а не под arm. Поэтому здесь нельзя просто транслировать вызовы напрямую.
Первое, что вам требуется, это слой эмуляции x86_64 для arm. Сейчас есть несколько решений для этого. Как минимум одно - box64, вы нашли по ссылке.
Вам, в вашем случае, нужно построить что-то вроде такого:
1. Эмулятор процессора через box64, qemu или иное средство виртуализации. Здесь же эмуляция видеокарты на процессоре (скорее всего у вас нет отдельной видеокарты)
2. Установка Windows в этом эмуляторе. (Можно и Linux, но он потребует лишний слой совместимости типа wine/proton, что не добавит производительности, а скорее сожрет ее)
3. Установка игры в Windows
4. Запуск

Я очень сомневаюсь, что результат удовлетворит своей производительностью и чистотой работы. В вашем случае установка и запуск приложений, собраных изначально под arm через android или linux даст во много раз лучший результат, чем через эмуляцию.
