### ISSUE TITLE
gamemoded процесс не улавливается Mangohud

### ISSUE THREAD

**Issue by Eljeyna** [Castro-Fidel/PortWINE#93]
![image](https://github.com/Castro-Fidel/PortWINE/assets/43903165/5930fe1e-b895-42c2-9226-6da67ea6fd1c)

Как видно на скриншоте, Mangohud ошибочно показывает "GAMEMODE off", хотя сам процесс запущен и работает нормально в системном мониторе. При запуске любой другой игры из Steam напрямую mangohud показывает ON.

**Comment by Castro-Fidel** [comment]
Не является багой, так как Mangohud внутри контейнера не видит запущен ли gamemode в системе. Если включить USE_SYSTEM_VK_LAYERS в настройка при запуске exe, должен начать показывать правильно.

**Comment by Eljeyna** [comment]
Да, это с включенным USE_SYSTEM_VK_LAYERS.

**Comment by Castro-Fidel** [comment]
При следующем глобальном обновление библиотек, обновим Мангохад с поддержкой определение gamemode в контейнере.
