### ISSUE TITLE
PortProton Woudn't  launch with pcmanfm

### ISSUE THREAD

**Issue by tomjpalamattam** [Castro-Fidel/PortWINE#98]
When i try to launch an exe file from portproton, I get this error

![2023-11-28-20:34:01](https://github.com/Castro-Fidel/PortWINE/assets/32675052/77fe141d-7fd3-440b-9f19-49f56823db7c)

I tried this with other file managers such as thunar, dophin & nautilus but they work fine. The only file manager where i encountered this issue is pcmanfm. I can also launch the game from terminal by 

 /home/tom/.local/share/PortWINE/PortProton/data/scripts/start.sh  /home/tom/Games-self/Files/Metal\ Gear\ Solid\ V\ The\ Phantom\ Pain/mgsvtpp.exe

but not using

/home/tom/.local/share/PortWINE/PortProton/data/scripts/start.sh  file:///home/tom/Games-self/Files/Metal%20Gear%20Solid%20V%20The%20Phantom%20Pain/mgsvtpp.exe

**Comment by Castro-Fidel** [comment]
Write a question to the pcmanfm developers.
